version: "3.8"
services:
  postgres-container:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - products-microservice-network
    
  mysql-container:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - products-microservice-network
    hostname: mysql-host-productsmicroservice


networks:
  products-microservice-network:
    driver: bridge